### ISSUE TITLE
Open source checklist

### ISSUE THREAD

**Issue by rathorevaibhav** [avantifellows/portal-frontend#44]
## Description
Consider the following items required for the open-source checklist:
- [ ] #45
- [ ] Issue templates, PR templates, Community guideline, Code of conduct
- [ ] Unit testing and code coverage
- [ ] Code quality, Static Code Analyzer
- [ ] AGPL License
- [ ] Dockerization?

**Comment by Akshanshkaushal** [comment]
@rathorevaibhav I would love to work upon this issue. Could you please assign this to me ?
